apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xt3c7mp4o-nodejs
  janus-idp.io/tekton: xt3c7mp4o-nodejs
  backstage.io/kubernetes-id: xt3c7mp4o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xt3c7mp4o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
